# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: First Contributions at devncode
description: >- # this means to ignore newlines until "baseurl:"
  Make your first open source contribution in 5 minutes
baseurl: "" # the subpath of your site, e.g. /blog
url: "first-contributions.devncode.tech" # the base hostname & protocol for your site, e.g. http://example.com

social:
  - title: "twitter"
    url: "https://twitter.com/devncode17"
  - title: "facebook"
    url: "facebook.com/devncode17"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UC0_WFaOYjFrZH2zxwI4BZOQ/videos"
  - title: "medium"
    url: "https://medium.com/devncode"
  - title: "github"
    url: "https://github.com/smkamranqadri/devncode.tech"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
